################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
    #tls: {}  # Empty tls block here to indicate Traefik handles TLS on this entry point
  local:   # New entrypoint for LAN-only HTTP traffic
    address: ":8088"

################################################################
# Traefik logs configuration
################################################################
log:
  level: DEBUG

################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true  # Enable insecure API for monitoring
  dashboard: true  # Enable Dashboard (set to false to disable it)

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
accessLog:
  filePath: /var/log/traefik/access.log
  format: json

################################################################
# Providers configuration
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"  # Docker socket
    exposedByDefault: false  # Do not expose containers by default
    defaultRule: "Host(`{{ .Name }}`)"  # Default rule for container names

  file:
    directory: "/etc/traefik/dynamic"  # Only load dynamic config files from here
    watch: true
  #file:
  #  directory: "/etc/traefik"  # Directory to watch for certificates (dynamic config)
  #  watch: true  # Watch for changes in dynamic config

################################################################
# Certificates Resolver for Cloudflare
################################################################
#certificatesResolvers:
  #cloudflare:
    #acme:
      #dnsChallenge:
        #provider: cloudflare  # Use DNS challenge for Cloudflare
      #email: ENTER_YOUR_CF_EMAIL  # Your Cloudflare email
      #storage: "/letsencrypt/acme.json"  # Path to store ACME certificates

